name 'secret_service'
maintainer 'Alexander Birk'
maintainer_email 'birk@pingworks.de'
license 'Apache 2.0'
description 'Installs/Configures secret_service'
long_description 'Installs/Configures secret_service'
version '0.1.20'
